//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 ComputerGraphics.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_ComputerGraphicTYPE         130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_LineDialog                  310
#define IDD_CircleDIALOG                312
#define IDD_EllipseDIALOG               314
#define IDD_LINETYPEDIALOG              316
#define IDD_LINEWIDTHDIALOG             319
#define IDD_TRANSFORMATION              321
#define IDD_Translation                 324
#define IDD_TranslationDialog           324
#define IDD_RECTDIALOG                  326
#define IDD_SCALINGDIALOG               328
#define IDD_ROTATIONDIALOG2D            330
#define IDD_SYMMETRICALDIALOG           332
#define IDD_SYMMETRICALDIALOG2D         332
#define IDD_SHEARDIALOG                 334
#define IDD_ROTATIONDIALOG3D            338
#define IDD_SYMMETRICALDIALOG3D         341
#define IDC_X1                          1000
#define IDC_Y1                          1001
#define IDC_EDIT1                       1001
#define IDC_X2                          1002
#define IDC_EDIT2                       1002
#define IDC_Y2                          1003
#define IDC_EDIT3                       1003
#define IDC_EDIT4                       1004
#define IDC_COMBO1                      1007
#define IDC_SLIDER1                     1008
#define IDC_EDIT5                       1009
#define IDC_STATIC_Z                    1017
#define IDC_EDIT6                       1018
#define IDC_EDIT7                       1019
#define IDC_EDIT8                       1020
#define IDC_STATIC_SCALING              1021
#define IDC_BUTTON1                     1023
#define IDC_BUTTON2                     1024
#define IDC_BUTTON3                     1025
#define IDC_BUTTON4                     1026
#define IDC_STATIC_ZSHEAR               1028
#define IDC_STATIC_ZX                   1029
#define IDC_STATIC_ZY                   1030
#define IDC_STATIC_XZ                   1031
#define IDC_STATIC_YZ                   1032
#define IDC_EDIT9                       1033
#define IDC_EDIT10                      1034
#define IDC_EDIT11                      1035
#define IDC_EDIT12                      1036
#define IDC_BUTTON5                     1039
#define IDC_BUTTON6                     1040
#define IDC_BUTTON7                     1041
#define ID_LINE                         32771
#define ID_FRACTAL_SNOW                 32772
#define ID_FRACTAL_SPIRAL               32773
#define ID_32774                        32774
#define ID_32775                        32775
#define ID_32776                        32776
#define ID_LINE_DDA                     32777
#define ID_LINE_BRESENHAMM              32778
#define ID_LINE_IMPROVEDBRESENHAM       32779
#define ID_CIRCLE_EASYFUNCTION          32780
#define ID_CIRCLE_MIDPOINTBRESENHAM     32781
#define ID_LINE_MIDBRESENHAM            32782
#define ID_LINE_BRESENHAM               32783
#define ID_CIRCLE_MIDBRESENHAM          32784
#define ID_ELLIPSE_MIDBRESENHAM         32785
#define ID_AREAFILLING_EDGEFILLING      32786
#define ID_AREAFILLING_SPREADFILLING    32787
#define ID_AREAFILLING_BOUNDARYFILL     32788
#define ID_AREAFILLING_FLOODFILL        32789
#define ID_AREAFILL_FLOODFILL           32790
#define ID_AREAFILL_BOUNDARYFILL        32791
#define ID_FILL_FLOOD                   32792
#define ID_FILL_BOUNDARY                32793
#define ID_LINE_TYPE                    32794
#define ID_LINE_WIDTH                   32795
#define ID_TYPE_SOLID                   32796
#define ID_TYPE_DASH                    32797
#define ID_TYPE_DOT                     32798
#define ID_2D_TRANSLATION               32801
#define ID_2D_SCALING                   32802
#define ID_2D_ROTATION                  32803
#define ID_2D_SYMMETRICAL               32804
#define ID_2D_SHEAR                     32805
#define ID_3D_TRANSLATION               32806
#define ID_3DTRASFORMATION_SCALING      32807
#define ID_3DTRASFORMATION_ROTATION     32808
#define ID_3DTRASFORMATION_SYMMETRICAL  32809
#define ID_3DTRASFORMATION_SHEAR        32810
#define ID_3D_ROTATION                  32811
#define ID_3D_SCALING                   32812
#define ID_3D_SYMMETRICAL               32813
#define ID_3D_SHEAR                     32814

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        343
#define _APS_NEXT_COMMAND_VALUE         32815
#define _APS_NEXT_CONTROL_VALUE         1042
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
